### ISSUE TITLE
tc bot

### ISSUE THREAD

**Issue by Webx123** [Ruddernation-Designs/html5-contact-form-with-Google-maps#1]
On your tc bot how would i add where it autobans tinychat urls? ppl keep spamming my room i want any tinychat.com/blablah auto banned

**Comment by Ruddernation-Designs** [comment]
Hi @Webx123 
I've now opened the issues for the TC bot again so could you post the issue there and I'll work on it later today.
[https://github.com/Tinychat/Tinychat-Bot/issues](url)
